# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://cdn.cocoapods.org/' # CDN加速

target 'APMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APMDemo
  pod 'DinergateBrain', '0.1.0'
  pod 'SQLite.swift'
  target 'APMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dinergate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QAIsAngry
  pod 'DinergateBrain', '0.1.0'
  pod 'SQLite.swift'
  target 'DinergateTests' do
    # Pods for testing
  end

end
